fwk_module: add debug message for module processing
ARM-software/SCP-firmware pull request #399
Opened 2021-01-11 12:17 UTC by iwishguo

When SCP firmware hangs in development, it is not very easy to find
which module and which stage of the module causes the hang.

Add debug messages using cli_printf() in the module processing
framework to make it easier to find which piece of code dies.

Signed-off-by: Heyi Guo <guoheyi@linux.alibaba.com>

2021-01-12 15:29 UTC, tarek-arm requested changes
Can you please use FWK_LOG_TRACE for this purpose? You can change the log level using a command-line option LOG_LEVEL=TRACE. 
Also, can you please add more description to the message to make it clear. You can use __func__ in your string if that helps. 
We are using [MOD] to identify messages from this file so it is better to do the same.
If possible please reduce the number of messages to improve readability.

2021-01-13 09:16 UTC, iwishguo commented
Does FWK_LOG_TRACE depend on the serial port and log module? If it does, then the firmware may still hang silently without any last word.

2021-01-13 11:28 UTC, CJKay commented
> 
> 
> Does FWK_LOG_TRACE depend on the serial port and log module? If it does, then the firmware may still hang silently without any last word.

Both the logging API and the debugger API output are routed through the I/O API (see [here](https://github.com/ARM-software/SCP-firmware/blob/2a519a7f5b939847c05596328db2e136ce08b86c/framework/src/fwk_log.c#L243) and [here](https://github.com/ARM-software/SCP-firmware/blob/2a519a7f5b939847c05596328db2e136ce08b86c/debugger/src/cli/cli.c#L527)).

The debugger API output is always written to the I/O API's [standard output stream](https://github.com/ARM-software/SCP-firmware/blob/b8e4d2500c484e9e92e650e08047a926cfbc7727/framework/include/fwk_io.h#L500-L508), which is configured on a per-platform basis through [`FMW_IO_STDOUT_ID`](https://github.com/ARM-software/SCP-firmware/blob/b8e4d2500c484e9e92e650e08047a926cfbc7727/framework/include/fwk_io.h#L76-L88). For example, [Juno defines its standard output entity to be UART0](https://github.com/ARM-software/SCP-firmware/blob/b8e4d2500c484e9e92e650e08047a926cfbc7727/product/juno/scp_ramfw/fmw_io.h#L15).

The logging API output is written to the logging API's [log drain stream](https://github.com/ARM-software/SCP-firmware/blob/2a519a7f5b939847c05596328db2e136ce08b86c/framework/src/fwk_log.c#L37), which is configured on a per-platform basis through [`FMW_LOG_DRAIN_ID`](https://github.com/ARM-software/SCP-firmware/blob/2a519a7f5b939847c05596328db2e136ce08b86c/framework/include/fwk_log.h#L67-L78). If it hasn't been configured (which, as of today, it isn't on any platform), it defaults to the I/O API's standard output stream. So, on all platforms currently, `cli_printf()` and `FWK_LOG_X()` print in exactly the same way.

Output that goes through the I/O API - including output written using either the logging API or the debugger API - does not require its modules to have successfully initialised to be used. Instead, any module that accepts standard I/O operations can provide [an I/O adapter](https://github.com/ARM-software/SCP-firmware/blob/2a519a7f5b939847c05596328db2e136ce08b86c/framework/include/fwk_io.h#L120-L199), which allows it to be used outside of the conventional module subsystem (and, as such, before the module subsystem has started, or if it has crashed). For an example of a module that does that, [see the PL011](https://github.com/ARM-software/SCP-firmware/blob/2a519a7f5b939847c05596328db2e136ce08b86c/module/pl011/src/mod_pl011.c#L633-L639).

So, to answer your question:

> Does `FWK_LOG_TRACE` depend on the serial port?

It does not, but it may use it if your firmware is configured to do so.

> Does `FWK_LOG_TRACE` depend on the log module?

It depends only on the I/O adapter of the module, separate from the rest of the module system, and does not rely on the functioning of the scheduler (unless log buffering is enabled, but this is disabled for debug builds anyway and may optionally be disabled for release builds).

Hope that helps!

2021-01-14 03:52 UTC, iwishguo commented
Aha, it seems the log framework has changed a lot in the mainline since I last navigated the code...

2021-01-14 11:22 UTC, CJKay commented
Ah, yes, the logging machinery underwent a bit of an overhaul about half way through mid-2020. That was predominantly driven by the need to use the logging facilities outside of the module runtime, for such cases as this one. 🙂

2022-10-20 08:25 UTC, closed without merging

2022-10-20 08:27 UTC, tarek-arm commented
Not active for a long time. If still required a new PR can be created.