cli: fix escape buffer overflow check
ARM-software/SCP-firmware pull request #443
Opened 2021-03-18 13:55 UTC by zhilongwb

This commit add escape buffer overflow check when cli receive
escape sequence(cursor position response). escape buffer size
is 8 bytes, the last byte used to store string end symbol '\0'.
So the longest string escape buffer can save is 7 bytes. But in
some console or tool, the cursor position response sequence is
more then 7 bytes, and escap buffer will overflow. This patch
fix it.

Signed-off-by: Zhilong Wubin <zhilong.wb@alibaba-inc.com>

2021-03-22 11:33 UTC, tarek-arm commented
Jenkins: OK to test.

2021-03-23 14:49 UTC, tarek-arm requested changes
Can you please add space after if to follow the coding style?
`
diff --git a/debugger/src/cli/cli.c b/debugger/src/cli/cli.c
index 85b93859..6fc7192e 100644
--- a/debugger/src/cli/cli.c
+++ b/debugger/src/cli/cli.c
@@ -973,7 +973,7 @@ static uint32_t cli_get_command(
         if (flag_escape_sequence == true) {
             /* Prevent escape buffer overflow, Only save first 7 bytes data of
              * escape sequences. */
-            if(escape_index >= 7) {
+            if (escape_index >= 7) {
                 escape[escape_index] = c;
                 escape[escape_index + 1] = 0;
                 escape_index = escape_index + 1;
`

2021-03-26 03:33 UTC, zhilongwb commented
> Can you please add space after if to follow the coding style?
> `diff --git a/debugger/src/cli/cli.c b/debugger/src/cli/cli.c
> index 85b93859..6fc7192e 100644
> --- a/debugger/src/cli/cli.c
> +++ b/debugger/src/cli/cli.c
> @@ -973,7 +973,7 @@ static uint32_t cli_get_command(
> if (flag_escape_sequence == true) {
> /* Prevent escape buffer overflow, Only save first 7 bytes data of
> * escape sequences. */
> 
> * ```
>          if(escape_index >= 7) {
>   ```
> 
> * ```
>          if (escape_index >= 7) {
>              escape[escape_index] = c;
>              escape[escape_index + 1] = 0;
>              escape_index = escape_index + 1;`
>   ```

Hi admin, thanks for your comments. I have add space after if. please review again.

2021-03-26 09:43 UTC, merged

2021-03-26 09:58 UTC, zhilongwb commented
Hi admin. This is my first patch submit by github. The last modification was edit from the browser, and this may cause some wrong commit message. Is there any remedies for the commit message? sorry for my mistake.