product/n1sdp: Enable non-secure CoreSight access in C2C setup
ARM-software/SCP-firmware pull request #467
Opened 2021-05-10 12:34 UTC by himsha01

This patch enables non-secure AXI access to CoreSight components
in both the primary and secondary boards in C2C setup.

Signed-off-by: Himanshu Sharma <Himanshu.Sharma@arm.com>
Change-Id: I000485fd30f87579b2b0a9b7f3935fe7ead99a7b

2021-05-10 13:00 UTC, nicola-mazzucato-arm commented
@manojkumar-arm can you pls approve this?

2021-05-10 13:21 UTC, manojkumar-arm requested changes
Added a comment in the code changes. Can you please take a look?

2021-05-11 08:01 UTC, himsha01 commented on product/n1sdp/module/n1sdp_system/src/mod_n1sdp_system.c
> +        /* Enable non-secure CoreSight debug access for secondary board */
@manojkumar-arm please check the recent changes

2021-05-11 09:14 UTC, manojkumar-arm approved these changes

2021-05-11 13:10 UTC, nicola-mazzucato-arm requested changes
@himsha01 there are trailing spaces after 0xFFFFFFFF; which need to be removed.
thanks

2021-05-11 14:59 UTC, nicola-mazzucato-arm approved these changes

2021-05-11 15:00 UTC, merged