clock: Fix call to get_state to use driver id instead of clock id
ARM-software/SCP-firmware pull request #626
Opened 2022-03-28 16:50 UTC by yaronm-hailo

When calling the clock driver's get_state API, the provied id should be
the driver element id, and not the clock's element id.
Fixed a call to get_state that was using the clock id.

2022-03-28 22:44 UTC, nicola-mazzucato-arm requested changes
Hi, @yaronm-hailo thanks for finding this.
Can you please make sure the indentation is correct? We suggest to use clang-format (please note that the formatter should run only on the diff, otherwise it may format the entire file).
Thanks

2022-03-29 07:09 UTC, yaronm-hailo commented
@nicola-mazzucato-arm I've ran clang-format on this file and the indentation is correct.

2022-03-29 08:39 UTC, nicola-mazzucato-arm commented
@yaronm-hailo thanks for confirming. the patch LGTM. We are currently finalising the next release and will merge this as soon as it's completed. Thank you.

2022-03-29 16:29 UTC, nicola-mazzucato-arm approved these changes

2022-04-05 10:51 UTC, merged