Optee smt unitary test
ARM-software/SCP-firmware pull request #834
Opened 2023-08-28 12:45 UTC by vingu-linaro

Add unitary test for optee/smt module

The unitary test covers 100% line code

2023-08-28 12:46 UTC, vingu-linaro commented
@mohamedasaker-arm 
This is the 3rd unitary test for optee/smt

2023-08-30 16:45 UTC, mohamedasaker-arm requested changes

2023-08-30 16:45 UTC, mohamedasaker-arm commented on module/optee/smt/test/mod_optee_smt_unit_test.c
> +void test_mailbox_smt_bind_round0(void)
The function name doesn't reflect this part. "and others except for round 1"
Can we say something like ..bind_rounds_except_round1?

2023-08-30 16:45 UTC, mohamedasaker-arm commented on module/optee/smt/test/mod_optee_smt_unit_test.c
> +void test_mailbox_smt_bind_round0(void)
or maybe bind_trivial_rounds
anything indicate that it's not only round0 and they are of a specific nature

2023-08-30 16:45 UTC, mohamedasaker-arm commented on module/optee/smt/test/mod_optee_smt_unit_test.c
> +    secure = 0xAA;
why not true/false? and I believe false here would be better

2023-08-30 16:45 UTC, mohamedasaker-arm commented on module/optee/smt/test/mod_optee_smt_unit_test.c
> +    secure = 0xAA;
why not secure=true?

2023-08-30 16:45 UTC, mohamedasaker-arm commented on module/optee/smt/test/mod_optee_smt_unit_test.c
> +    status = smt_write_payload(channel_id, 0, (const void*)fake_payload, channel_ctx->max_payload_size+1);
Minor: format:  `channel_ctx->max_payload_size + 1`

2023-08-30 16:45 UTC, mohamedasaker-arm commented on module/optee/smt/test/mod_optee_smt_unit_test.c
> +void fake_fwk_str_memcpy(void *dest, const void *src, size_t count, int iteration)
Minor:
As I understand from your PR: you try to make helper/callback functions before usage
However, I don't see it in `test_smt_write_payload_early` So could you move it before `test_smt_write_payload`?

2023-08-30 16:45 UTC, mohamedasaker-arm commented on module/optee/smt/test/mod_optee_smt_unit_test.c
> +}
I suggest for these helper functions to remove the "test" prefix
to not conflict with the real tests.

2023-12-14 11:20 UTC, nicola-mazzucato-arm commented
Agreed with @vingu-linaro to bring this PR over gitlab.
Thanks

2024-02-02 16:15 UTC, leandro-arm commented
# Hello! 👋

Thank you for your contribution to the SCP-firmware Project!

SCP-firmware contributions can only be submitted through [GitLab](https://gitlab.arm.com/firmware/SCP-firmware). This GitHub repo is accessible as a Read-Only mirror and it is not able to accept contributions for the project.

This PR has been migrated to: https://gitlab.arm.com/firmware/SCP-firmware/-/merge_requests/834

The SCP-firmware team

2024-02-02 16:15 UTC, closed without merging