module/power_domain: Refactor the power domain module
ARM-software/SCP-firmware pull request #870
Opened 2023-11-13 17:33 UTC by Jmc18134

This PR breaks up the power domain module to make things more readable and easier to modify. 
Notification-related functions are now only included when notifications are enabled. State-related utilities and notifications have been moved to their own files.

2023-11-14 09:02 UTC, nicola-mazzucato-arm requested changes
pls rephrase commit title to be within 72 chars. thanks

2023-11-14 09:04 UTC, nicola-mazzucato-arm requested changes
Commit msg to be within 80 chars please.

2023-11-21 12:31 UTC, nicola-mazzucato-arm commented
Jenkins: ok to test

2023-11-22 15:41 UTC, leandro-arm approved these changes

2023-11-22 16:02 UTC, nicola-mazzucato-arm approved these changes

2023-11-22 16:02 UTC, merged